-- 초기 데이터 설정
INSERT INTO POINT_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('MAX_EARN_PER_ONCE', '100000', '최대 100000포인트까지 적립 가능');
INSERT INTO POINT_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES ('MAX_BALANCE_LIMIT', '100000', '최대 100000포인트까지 보유 가능');