CREATE TABLE POINT_CONFIG (
  CONFIG_KEY   VARCHAR(50) PRIMARY KEY COMMENT '설정 키',
  CONFIG_VALUE VARCHAR(100) NOT NULL COMMENT '설정 내용 값',
  DESCRIPTION  VARCHAR(255) COMMENT '해당 설정에 대한 상세 설명'
) COMMENT='포인트 정책 설정 정보';

CREATE TABLE POINT_EARNING (
   ID              BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '적립 ID',
   MEMBER_ID       BIGINT                 NOT NULL COMMENT '회원 ID',
   POINT_KEY       VARCHAR(100)           NOT NULL COMMENT '포인트 키 (중복 적립 방지)',
   ORIGINAL_AMOUNT DECIMAL(10, 0)         NOT NULL COMMENT '최초 적립된 금액',
   BALANCE_AMOUNT  DECIMAL(10, 0)         NOT NULL COMMENT '사용 가능한 잔여 포인트',
   IS_MANUAL       TINYINT(1) DEFAULT 0            COMMENT '관리자 수기 적립 여부 (0: false, 1: true)',
   EXPIRE_at       DATETIME               NOT NULL COMMENT '포인트 만료 예정 일시',
   VERSION         BIGINT     DEFAULT 0   NOT NULL COMMENT '낙관적 락(Optimistic Lock)을 위한 버전 번호',
   CREATED_AT      DATETIME   DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
   UPDATED_AT      DATETIME   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
   UNIQUE KEY UK_POINT_KEY (POINT_KEY),
   INDEX IDX_MEMBER_ID_EXPIRE_AT (MEMBER_ID, EXPIRE_at)
) COMMENT='포인트 적립 내역 및 잔액 관리';

CREATE TABLE POINT_LEDGER (
  ID          BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '원장 ID',
  MEMBER_ID   BIGINT NOT NULL COMMENT '회원 ID',
  EARNING_ID  BIGINT NOT NULL COMMENT '연관된 포인트 적립 ID',
  TRADE_NO    VARCHAR(100) COMMENT '거래 번호 (주문번호 또는 트랜잭션 ID)',
  AMOUNT      DECIMAL(10, 0) NOT NULL COMMENT '변동 포인트',
  EVENT_TYPE  VARCHAR(20) NOT NULL COMMENT '이벤트 유형 (EARN, REVOKE, USE, REFUND, EXPIRE_REINSTATE)',
  DESCRIPTION VARCHAR(255) COMMENT '상세 내역',
  CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
  CONSTRAINT FK_LEDGER_EARNING FOREIGN KEY (EARNING_ID) REFERENCES POINT_EARNING(ID),
  INDEX IDX_TRADE_NO (TRADE_NO)
) COMMENT='포인트 원장 (적립/사용 상세 트랜잭션 기록)';